# Generated by Django 5.1 on 2024-09-16 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='user_tpye',
            new_name='user_type',
        ),
    ]
