# Generated by Django 5.1 on 2024-09-17 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_course_seission_year'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Seission_year',
            new_name='Session_year',
        ),
    ]
