# Generated by Django 5.1 on 2024-09-25 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_staffnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffnotification',
            name='status',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
