# Generated by Django 5.1 on 2024-09-26 09:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_staffnotification_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staffnotification',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='staffnotification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
